### ISSUE TITLE
物品源显示错误

### ISSUE THREAD

**Issue by 157946a** [Micalhl/TrHologram#2]
物品源就是和trmenu的材质一样,挂钩某个插件,使用某个插件的功能,写法是{item=source:headdatabase:164}正常来说,应该显示一个木头,上面写着一个A的字样的头颅,他显示的是基岩,用这个功能前,要有trmenu3.0+,headdatabase

**Comment by Micalhl** [comment]
已修复, 请使用 pre9 或以上版本.
