### ISSUE TITLE
无法下载TrHologram

### ISSUE THREAD

**Issue by fenglanxi** [Micalhl/TrHologram#33]
actions下载不了了

**Comment by YuanYuanOwO** [comment]
https://github.com/Micalhl/TrHologram/actions/runs/1572745350

**Comment by z446066151** [comment]
actions下载不了！是网站问题还是我的问题？

**Comment by Micalhl** [comment]
actions 当时的构建失败了，一会应该有个构建成功的升级版本下一下就行。
