### ISSUE TITLE
无法高亮显示

### ISSUE THREAD

**Issue by Super-10** [Micalhl/TrHologram#6]
当文字部分被物品挡住之后无法高亮显示 
希望能增加个高亮显示{highlight}
![image](https://user-images.githubusercontent.com/65401527/130202897-518b0ed4-f657-4310-b122-8d3ddfb94abc.png)

**Comment by Micalhl** [comment]
这个好像本来就是这样的吧。。就跟你沙子掉下来你玩家被卡在方块里面是黑色的一样

**Comment by Super-10** [comment]
> 这个好像本来就是这样的吧。。就跟你沙子掉下来你玩家被卡在方块里面是黑色的一样

但是Holographic Displays可以把暗的字体给高亮显示
